services:
  mysql:
    image: mysql:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork
  myapp:
    image: nginx:latest
    ports: 
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge